background #000000
foreground #e5e1cf
cursor #f19618
selection_background #243340
color0 #4c4c4c
color8 #737373
color1 #ff6685
color9 #ffa8ba
color2 #a6eba6
color10 #c5ebc5
color3 #ffdc72
color11 #f9f9a5
color4 #5dc6f5
color12 #8ddbff
color5 #ff8fff
color13 #ffabff
color6 #86d1d7
color14 #b0f0f0
color7 #dbdbdb
color15 #ffffff
selection_foreground #0e1419
