general {
    disable_loading_bar = true
    grace = 3
    hide_cursor = true
    no_fade_in = false
}

background {
    #path = screenshot
    path = /home/zettez/Pictures/hsr.png
    blur_passes = 3
    blur_size = 4
}

image {
    path = ~/.face
    size = 250
    position = -700, 100
    rounding = -1
    border_size = 4
    border_color = rgb(0, 0, 0)
    halign = center
    valign = center
}

input-field {
    size = 200, 40
    position = -700, -75
    rounding = 1
    # dots_center = true
    fade_on_empty = false
    font_color = rgb(202, 211, 245)
    inner_color = rgb(91, 96, 120)
    outer_color = rgb(24, 25, 38)
    outline_thickness = 2
    placeholder_text = <span foreground="##cad3f5">PASSWORD HERE</span>
    # shadow_passes = 2
}

